---
dist: 'bionic'

language: 'go'

go:
  - '1.13.x'

# skip the 'go get' setup step
install: true

env:
  DEBIAN_FRONTEND: 'noninteractive'
  CGO_CPPFLAGS: '-I/usr/include/collectd/core/daemon -I/usr/include/collectd/core'
  GOFLAGS: '-mod=vendor'

before_install:
  - sudo apt-get install -y collectd-dev

script:
  - go test -v ./...
  - go build -buildmode=c-shared -o prometheus_scraper.so

