---
debug: false

scrape_timeout: '10s'

scrape_configs:
  'coredns':
    target: 'coredns'
    scrape_timeout: '5s'

  'traefik':
    target: 'traefik'
    basic_auth:
      username: 'plop'
      password: 'toto'
    labels:
      production_ready: false
      integer_value: 32
